version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/consumer
    volumes:
      - ./config:/app/config
    networks:
      - shared_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: simpleapi_database
      KAFKA_BROKER: kafka:9092

networks:
  shared_network:
    external: true

