minio:
  endpoint: "my-minio-file.darkube.app"
  accesskey: "c4JrL9xJILzgIH7zRu4y"
  secretkey: "MMMIq1AQSoRiCsSU6WdlOLIAVv7KmTj4Y4SgxzhL"
  bucket: "file-bucket"

kafka:
  broker: kafka:9092
  topic: upload_file_topic
  group_id: file_consumer_group